name: Publish API Docs

on:
  push:
    branches: [docs]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - run: git lfs checkout

      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'yarn'

      - name: Install
        run: |
          npm install -g yarn
          yarn --version
          yarn install --immutable-cache

      - name: Build docs
        run: yarn run build:docs

      - name: Analysis API
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: p5-analysis/build/docs
          target-folder: p5-analysis

      - name: Server API
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: p5-server/build/docs
          target-folder: p5-server
