name: Test

on:
  push:
    branches: [master]
  pull_request:
    branches: [main, master]

jobs:
  build:
    strategy:
        matrix:
          os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - name: Install
        run: npx lerna install

      - name: Lint and Test
        run: |
          # npm run lint
          npm test
