name: Test

on:
  push:
    branches: [master]
  pull_request:
    branches: [main, master, test-workflow]

jobs:
  build:
    strategy:
        matrix:
          os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - name: Install
        run: |
          npm install
          npx lerna install
          ls */node_modules
          npx lerna run install
          ls */node_modules

      - name: Lint and Test
        run: |
          npm run lint
          npm test
